#!/bin/sh

usage()
{
  echo 'master <target> <failOnError?> [<property=value> ...]'
}

if [ "$1" == "" ]
then
  usage
  exit 1
fi


CMD="nant /f:BuildScripts/master.build $1"

if [ "$2" != "" ]
then
  CMD="$CMD -D:fail.on.error=$2"
fi

while [ "$3" != "" ]
do
  CMD="$CMD -D:$3"
  shift
done

echo $CMD

$CMD

