#!/bin/sh

PROC=`basename $BASH_SOURCE`
TEMPLATES_DIR=BuildScripts/templates

usage()
{
  echo "$PROC <template> <sln.name>"
  echo "Templates: "
  for template in $(find $TEMPLATES_DIR -mindepth 1 -maxdepth 1 -type d)
  do
    echo "  $(basename $template)"
  done
}


if [ "$1" == "" -o "$2" == "" ]
then
  usage 
  exit 1
fi


TEMPLATE=$TEMPLATES_DIR/$1
SOLUTION=$2

if [ -d $SOLUTION ]
then
  echo "Solution already exists: $SOLUTION"
  exit 2
fi

exmon FilterDirectoryTree $TEMPLATE . "SOLUTION_NAME=$SOLUTION"

